---
.travis.yml:
  secure: "k0EC65NpSE99x7MGMjDaD0uOGu59pfQ11huqvKqDFUPabuRV3BU+asYSUmaZkI4gTQe0aREysXVYcqAmdcSo6zOqUsaS9k6jVTqgM3XJyZX49DedJZozZ6o+0NkvHkGsaQTIhOBlDxndu5QAJ6aUEwm/HdmhMpVQzFo6BARAKoA="
...
