fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.2.1"
    portage: "git://github.com/gentoo/puppet-portage.git"
  symlinks:
    apache: "#{source_dir}"
